server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/f1_ums?useSSL=false&allowPublicKeyRetrieval=true
    username: milos
    password: milos

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true

  jackson:
    serialization:
      fail-on-empty-beans: false
